name: "Terraform"

on:
  push:
    branches:
      - "main"

jobs:
  terraform-apply:
    name: "Terraform: Apply in production"
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Apply
        run: |
          terraform init --upgrade
          terraform apply -auto-approve -input=false
