name: "Terraform"

on:
  push:
    branches:
      - "main"

jobs:
  terraform-apply:
    name: "Apply terraform on approval"
    runs-on: ubuntu-latest
    environment:
      name: tf-apply
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Apply
        run: |
          terraform init --upgrade
          terraform apply -auto-approve -input=false

  terraform-destroy:
    name: "Destroy terraform on approval"
    needs: [terraform-apply]
    runs-on: ubuntu-latest
    environment:
      name: tf-destroy
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Destroy
        run: |
          terraform init
          terraform destroy -auto-approve
